CREATE TABLE IF NOT EXISTS INSTRUCTOR (
    FisCode TEXT PRIMARY KEY,
    Name TEXT NOT NULL,
    Surname TEXT NOT NULL,
    BirthDate TEXT NOT NULL,
    Email TEXT NOT NULL,
    Telephone_Number TEXT
);

CREATE TABLE IF NOT EXISTS COURSES (
    CodC TEXT PRIMARY KEY,
    Name TEXT NOT NULL,
    CType TEXT NOT NULL,
    Level INTEGER NOT NULL CHECK(Level BETWEEN 1 AND 4)
);

CREATE TABLE IF NOT EXISTS PROGRAM (
    FisCode TEXT NOT NULL,
    Day TEXT NOT NULL,
    StartTime INTEGER NOT NULL,
    Duration INTEGER NOT NULL,
    CodC TEXT NOT NULL,
    Room TEXT NOT NULL,
    PRIMARY KEY (FisCode, Day, StartTime, CodC),
    FOREIGN KEY (FisCode) REFERENCES INSTRUCTOR(FisCode),
    FOREIGN KEY (CodC) REFERENCES COURSES(CodC)
);
